objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Customer_Segment__c</fullName>
        <label>Customer Segment</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Percentage__c</fullName>
        <label>Discount Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TriggerHandler.cls
/**
 * @description TriggerHandler
 */
public class TriggerHandler 
{
    /**
     * @description triggerDiscount
     * @param newOpportunities list to pass discount parameters
     */
    public static void triggerDiscount(List<Opportunity> newOpportunities) 
    {
        for(Opportunity oppo : newOpportunities)
    {
        decimal discount = DiscountCalculator.calculateDiscount(oppo.Product_Category__c,oppo.Customer_Segment__c);
        oppo.Discount_Percentage__c = discount;
    }
    }
}